name: instagram_clone_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.20

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # UI and utilities
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ic_instagram.svg
